EXENAME  = mpiatom
### ------ Personal PC compilation ------------
#CXX     = g++ #icc
#CPPFLAGS = -std=c++11
#LDFLAGS  = -llapack -lblas

### ------ Newton compilation ------------
### MUST USE: module load gcc/4.8.2
CXX = mpic++  ### Or use g++ (both works!)
# CPPFLAGS = -std=c++11
CPPFLAGS =
LDFLAGS = -lmkl_intel_lp64 -lmkl_core -lmkl_intel_thread -ldl -lpthread -lm -qopenmp -liomp5

### --- turn on for debugging -----------
CPPFLAGS += -Isrc
#CPPFLAGS += -Wall -Werror -Wextra #### This enables warnings with extra debugging
#CPPFLAGS += -g3 #### link gdb to file system of program
CPPFLAGS += -O3 #### Reduce compilation time and make debugging produce the expected results.
STRIP_COMMAND = true #### Keeps lines in the executable for debugging

$(EXENAME): clean main.o
    module load openmpi/2.1.1
    $(CXX) $(CPPFLAGS) -o $(EXENAME)  main.cpp

all: $(EXENAME)

submit:
    qsub submit.pbs


clean:
	rm -f $(EXENAME) *.o
    rm -f *~ *.o* *.e*

######## End of Makefile ########
